baseURL = "https://brage-blog.pages.dev/"
title = "Brage N. Reitan"
enableRobotsTXT = true

[params]
name = 'Brage N. Reitan'


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true



      resources/_gen/assets/scss/sass/js